version: '3.9'
services:
  api-graphql:
    container_name: "api-graphql"
    build: .
    ports:
      - "3000:80"
    depends_on:
      - mariadb
    volumes:
      - "/app/node_modules"

  phpmyadmin:
    container_name: "demo-graphql-phpmyadmin"
    image: phpmyadmin:5.1
    ports:
      - "8081:80"
    environment:
      PMA_host: db
    depends_on:
      - db

  db:
    container_name: "demo-graphql-db"
    build: ./data
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "graphql"
    volumes:
      - "data:/var/lib/mysql"


volumes:
  data:




